---
# tasks file for default


- name: playbook de usuarios padroes
  include: user.yaml

- name: pacotes padroes para debian
  include: debian.yaml
  when: ansible_os_family == "Debian"

- name: pacotes de padroes para RedHat
  include: centos.yaml
  when: ansible_os_family == "RedHat"

- name: arquivos padroes para todas as maquinas
  include: arquivo.yaml

