---

- name: criando usuarios padroes
  user:
   name: "{{item.nome}}"
   shell: "{{item.bash}}"
   password: "{{item.senha}}"
   home: "{{item.home}}"
  with_items:
   - { nome: pedrin, bash: /bin/bash, senha: '$1$5j7Y24oT$qEBHo2in2pGCz1b0Ds3Iq0', home: /srv/pedrin }
   - { nome: developer, bash: /bin/bash, senha: '$1$5j7Y24oT$qEBHo2in2pGCz1b0Ds3Iq0', home: /srv/developer }
   - { nome: devops, bash: /bin/bash, senha: '$1$5j7Y24oT$qEBHo2in2pGCz1b0Ds3Iq0', home: /srv/devops }

