

- name: meu segundo playbook
  hosts: all
  tasks:
     - name: adicionando usuario developer
       user:
         name: developer
         password: '$1$uUlvpNaT$o9leWJNj0ptUEHeP22P/s.'
         shell: /bin/bash

     - name: adicionando usuario pedrin
       user:
         name: pedrin
         password: '$1$uUlvpNaT$o9leWJNj0ptUEHeP22P/s.'
         shell: /bin/bash


